version: '3.3'
services:
  web:
    build: ./spring-app/
    image: yanivomc/spring-music:8
    restart: always
    ports:
      - 8080:8080
      - 8090:8080
    networks:
      - dblayer
      - app_layer
  redis:
    image: redis
    ports:
      - 6379:6379
  nginx:
    image: nginx
    ports:
      - 80:80

  db_mysql:
    image: wangxian/alpine-mysql
    environment: # env variables
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - dblayer
networks:
  dblayer:
  app_layer:
