version: '3.3'
services:
  web:
   build: ./spring-app/
   image: yanivomc/spring-music:latest
   ports:
     - 8080:8080
   networks:
     - dblayer
     - applayer

  redisdb:
     image: redis
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_DATABASE=music
     ports:
       - 6379:6379

  nginx:
    image: nginx
    ports:
      - 80:80
      
networks:
  dblayer:
  applayer:
